### ISSUE TITLE
Corregir los errores y warnings del archivo story-card-content.stories.ts

### ISSUE THREAD

**Issue by rolivencia** [cuentoneta/cuentoneta#810]
## Pasos para resolver el problema:
- Ir al archivo en la ruta **src/app/components/story-card-content/story-card-content.stories.ts**
- Resolver los errors y warnings que marca el linter en ese archivo

### Linter log:

- 3:24  warning  'DatePipe' is defined but never used       @typescript-eslint/no-unused-vars
- 14:10  warning  'provideRouter' is defined but never used  @typescript-eslint/no-unused-vars

**Comment by harsh-791** [comment]
i want to work on this issue. @rolivencia

**Comment by harsh-791** [comment]
i want to work on this issue. @rolivencia 
can i directly remove the DatePipe and provideRoute.
Also, in story constant, it was giving error due to missing resource parameter, so i fixed that by passing an empty resource array.
![Screenshot from 2024-07-17 02-29-20](https://github.com/user-attachments/assets/b3d069fa-acb2-487e-b22e-d932e3b4b746)

**Comment by rolivencia** [comment]
Hi @harsh-791. This specific issue aims to fix the eslint errors and warnings, no more and no less. We aim to focus later on setting the Storybook stories to work properly again, but I can open a new issue about this if you'd like to work on it.

Please let me know if that works for you.

**Comment by harsh-791** [comment]
so would it be all right if i just remove he DatePipe and provideRoute and not do any other changes

**Comment by rolivencia** [comment]
Yes, that'll make the linter to work properly. We can focus on making the Storybook story to work properly later @harsh-791.
